export const SET_DANH_SACH_PHIM = 'SET_DANH_SACH_PHIM'
export const SET_PHIM_DANG_CHIEU = 'SET_PHIM_DANG_CHIEU'
export const SET_PHIM_SAP_CHIEU = 'SET_PHIM_SAP_CHIEU'

export const SET_THONG_TIN_PHIM_EDIT = 'SET_THONG_TIN_PHIM_EDIT'